In [1]:
import numpy as np

np.min( x)

In [2]:
a=np.array([3,4,5,6])
print(np.min(a))

3


np.max( x )

In [3]:
print(np.max(a))

6


np.argmin( x )

In [4]:
print(np.argmin(a))#will tell me the pos of minimum value inside the np array

0


np.argmax( x )

In [5]:
print(np.argmax(a))

3


In [7]:
b=np.array([[3,4,5],[6,7,8]])
print(np.min(b,axis=1))#in row
print(np.min(b,axis=0))#in col

[3 6]
[3 4 5]


np.sqrt( x )

In [8]:
print(np.sqrt(b))

[[1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]


np.sin( x),np.cos( x )

In [10]:
c=np.array([3,4,5])
print(np.sin(c))
print(np.cos(c))

[ 0.14112001 -0.7568025  -0.95892427]
[-0.9899925  -0.65364362  0.28366219]


np.cumsum( x )

In [11]:
print(np.cumsum(a))

[ 3  7 12 18]
