In [1]:
import numpy as np

In [5]:
a=np.array([3,4,5])
print(a.shape)
b=np.array([[9],[7],[8]])
print(b.shape)
add=a+b
print(add)

(3,)
(3, 1)
[[12 13 14]
 [10 11 12]
 [11 12 13]]


In [10]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([10, 20, 30])
nadd=x+y
print(x.shape)
print(y.shape)
print(nadd)
print(nadd.shape)

(2, 3)
(3,)
[[11 22 33]
 [14 25 36]]
(2, 3)


The rule is simple between the two array's compare the element of both array from right side check if there is one in one of the array if yes then it will perform arithmetic or check if any of the elements is same in both the array for example if 3x1 is shape of an array and 3x3is a shape of another array here if we compare from the right side there is 1 and 3 and 3 is same on ther two so it will work

In [15]:
p=np.array([3,4,5])
print(p.shape)
q=np.array([[[3,4,5],[5,6,7],[7,8,9]]])
print(q.shape)
print(p)
print(q)
r=p+q
print(r)

(3,)
(1, 3, 3)
[3 4 5]
[[[3 4 5]
  [5 6 7]
  [7 8 9]]]
[[[ 6  8 10]
  [ 8 10 12]
  [10 12 14]]]
