In [1]:
import numpy as np

In [3]:
a=np.array([3,4,5,6])
print(a[3])

6


In [5]:
b=np.array([[4,5,6],[6,7,8]])
print(b[1,2])

8


In [20]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)
print(c[0,1,1])#here the 0 is the element of first bracket an 1 is the second row and another 1 is the middle column

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
5


Slicing

In [22]:
d=np.array([1,2,3,4,5,6,7,8,9])
print(d[1:6])#first pos to 5th pos

[2 3 4 5 6]


In [25]:
print(d[0:9:2])#oth pos to 8th pos with step 2

[1 3 5 7 9]


In [26]:
e=np.array([[1,2,3],[4,5,6]])
print(e)

[[1 2 3]
 [4 5 6]]


In [27]:
print(e[1,0:2])#here 1 is the row no and 0 is the first pos and 2 is the stop pos

[4 5]


In [28]:
f=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(f)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [31]:
print(f[0,1,:2])#here 0 is the first bracket, 1 is the second row,and 0 is the first pos, 2 is the stop pos

[4 5]
