In [1]:
import numpy as np

In [17]:
a=np.array([3,4,5,6,7,8,9])
print(a)
print()
for i in a:
    print(i,end=" ")


[3 4 5 6 7 8 9]

3 4 5 6 7 8 9 

In [19]:
b=np.array([[3,4,5],[6,7,8]])
print(b)
print()
for i in b:
    for j in i:
        print(j,end=" ")
    print()

[[3 4 5]
 [6 7 8]]

3 4 5 
6 7 8 


In [21]:
c=np.array([[[3,4,5],[5,6,7],[7,8,9]]])
print(c)
print()
for i in c:
    for j in i:
        for k in j:
            print(k,end=" ")
        print()
    print()

[[[3 4 5]
  [5 6 7]
  [7 8 9]]]

3 4 5 
5 6 7 
7 8 9 



In [22]:
for i in np.nditer(c):#nditer is used to print the values of an multidimensional array without going through multiple loops
    print(i,end=" ")

3 4 5 5 6 7 7 8 9 

In [29]:
for i in np.nditer(c,flags=['buffered'],op_dtypes=["S"]):
    print(i)

b'3'
b'4'
b'5'
b'5'
b'6'
b'7'
b'7'
b'8'
b'9'


In [30]:
for i,j in np.ndenumerate(c):#to get the index value of the element
    print(i,j)

(0, 0, 0) 3
(0, 0, 1) 4
(0, 0, 2) 5
(0, 1, 0) 5
(0, 1, 1) 6
(0, 1, 2) 7
(0, 2, 0) 7
(0, 2, 1) 8
(0, 2, 2) 9
