In [2]:
import numpy as  np

In [6]:
a=np.array([3,4,5,6])
b=np.array([6,7,8,9])

c=np.concatenate((a,b))#concatenate is used to merge two arrays in one
print(c)

[3 4 5 6 6 7 8 9]


In [8]:
d=np.array([[3,4,5],[5,6,7]])
e=np.array([[8,9,7],[4,5,6]])

f=np.concatenate((d,e),axis=1)#row wise
print(f)
g=np.concatenate((d,e),axis=0)#colrow wise
print(g)

[[3 4 5 8 9 7]
 [5 6 7 4 5 6]]
[[3 4 5]
 [5 6 7]
 [8 9 7]
 [4 5 6]]


In [11]:
h=np.stack((a,b),axis=1)#here i am doing colmn wise but by default stack function is row wise
print(h)

[[3 6]
 [4 7]
 [5 8]
 [6 9]]


In [13]:
i=np.hstack((a,b))#row wise
j=np.vstack((a,b))#col wise
k=np.dstack((a,b))#hight wise
print(i)
print(j)
print(k)

[3 4 5 6 6 7 8 9]
[[3 4 5 6]
 [6 7 8 9]]
[[[3 6]
  [4 7]
  [5 8]
  [6 9]]]


Split

In [16]:
x=np.array([3,4,5,6,7,8])
print(x)

y=np.array_split(x,3)#spliting purpose baed on no, and its type is list
print(y)
print(type(y))

[3 4 5 6 7 8]
[array([3, 4]), array([5, 6]), array([7, 8])]
<class 'list'>


In [18]:
z=np.array([[3,4,5],[6,7,8]])
print(z)
p=np.array_split(z,2)
print(p)

[[3 4 5]
 [6 7 8]]
[array([[3, 4, 5]]), array([[6, 7, 8]])]


In [19]:
q=np.array_split(z,2,axis=1)
print(q)

[array([[3, 4],
       [6, 7]]), array([[5],
       [8]])]
