In [1]:
import numpy as np

In [4]:
a=np.array([3,4,4,5,7,9,5,6,7,8,9])
x=np.where(a==4)#where is used to find the indexes of element
print(x)

(array([1, 2], dtype=int64),)


In [7]:
y=np.where((a%2)==0)
print(y)

(array([1, 2, 7, 9], dtype=int64),)


SearchSort

In [9]:
b=np.array([3,4,5,7,8,9])
print(b)
z=np.searchsorted(b,6)#it will give you the index where should you insert your value inside a sorted array
print(z)

[3 4 5 7 8 9]
3


In [10]:
z=np.searchsorted(b,[6,7,8])#we can pass a list of elements also
print(z)

[3 3 4]


Sort

In [12]:
c=np.array([5,3,7,4,9,6,8])
print(c)
print(np.sort(c))#sort is used to sort the array

[5 3 7 4 9 6 8]
[3 4 5 6 7 8 9]


In [13]:
d=np.array(['s','o','u','r','a','v'])
print(d)
print(np.sort(d))

['s' 'o' 'u' 'r' 'a' 'v']
['a' 'o' 'r' 's' 'u' 'v']


In [14]:
e=np.array([[1,5,7],[4,3,8]])
print(np.sort(e))

[[1 5 7]
 [3 4 8]]


Filter

In [16]:
s=[True,False,True,False,False,True]
new=d[s]
print(new)

['s' 'u' 'v']
