In [1]:
import numpy as np

In [10]:
a=np.array([[3,4,5],[6,7,8],[9,0,3]])
print(a)
print(a.dtype)
print(type(a))
print()

[[3 4 5]
 [6 7 8]
 [9 0 3]]
int32
<class 'numpy.ndarray'>



In [15]:
b=np.matrix([[3,4,5],[6,7,8],[9,0,3]])
print(b)
print(b.dtype)
print(type(b))
print()
c=np.matrix([[3,4,5],[6,7,8],[9,0,3]])
print(b)
d=b+c
print()
print(d)
d=b-c
print()
print(d)
d=b*c
print()
print(d)
print()
print(b.dot(c))

[[3 4 5]
 [6 7 8]
 [9 0 3]]
int32
<class 'numpy.matrix'>

[[3 4 5]
 [6 7 8]
 [9 0 3]]

[[ 6  8 10]
 [12 14 16]
 [18  0  6]]

[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[ 78  40  62]
 [132  73 110]
 [ 54  36  54]]

[[ 78  40  62]
 [132  73 110]
 [ 54  36  54]]
