In [1]:
import numpy as np

rand(): the function is used to generate a random value between O to I.

In [2]:
var1=np.random.rand(4)#here np.random.rand is used to create and np array with 4 random values
print(var1)

[0.48524915 0.37688237 0.5455672  0.12626432]


In [3]:
var2=np.random.rand(2,5)#here the dimesion is 2 with 5 rndom values in each dimesion
print(var2)

[[0.15904835 0.14408612 0.61202188 0.17759458 0.07823205]
 [0.62193595 0.09248695 0.65259071 0.08037888 0.08745703]]


randn(): the function is used to generate a random value close to zero. This may return positive or negative numbers as well.

In [4]:
var3=np.random.randn(5)
print(var3)

[ 0.8858416  -0.64359021 -1.08952676 -0.45307691 -0.48424654]


In [5]:
var4=np.random.randn(3,5)
print(var4)

[[ 0.16440682  0.13692069  1.9862206   0.86691824  1.78030135]
 [ 1.48881784  1.09847058 -0.58908991  0.10306405  0.25679582]
 [ 0.75738397 -0.71565441 -0.00218889 -0.28192087  0.64003983]]


ranf(): the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half-open interval [0.0, 1.0).

In [6]:
var5=np.random.ranf(5)
print(var5)

[0.69897861 0.0618909  0.59586951 0.91114529 0.17183595]


randint( ) : the fuction is used to generate a random number be in a given range.

In [7]:
var6=np.random.randint(1,5,7)#here it will create random 7 no's in range of one to five
print(var6)

[3 2 4 4 1 2 4]
