In [1]:
import numpy as np

In [2]:
revenue=np.array([[180,200,220],[24,36,40],[12,18,20]])
expense=np.array([[80,90,100],[10,16,20],[8,10,10]])

In [3]:
revenue

array([[180, 200, 220],
       [ 24,  36,  40],
       [ 12,  18,  20]])

In [4]:
expense

array([[ 80,  90, 100],
       [ 10,  16,  20],
       [  8,  10,  10]])

In [5]:
profit=revenue-expense
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [9]:
unit_sold=np.array([[30,40,50],[5,10,15],[2,5,7]])
price_per_unit=np.array([1000,400,1200])

In [10]:
unit_sold

array([[30, 40, 50],
       [ 5, 10, 15],
       [ 2,  5,  7]])

In [11]:
price_per_unit

array([1000,  400, 1200])

In [14]:
Total_Sale =np.dot(price_per_unit,unit_sold)
Total_Sale

array([34400, 50000, 64400])

In [15]:
revenue=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])

In [16]:
revenue

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

In [17]:
converion=75*revenue
converion

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [18]:
Sold=np.array([[50,60,25],[10,13,5],[40,70,52]])
price=np.array([20,30,15])

In [19]:
sale=np.dot(price,Sold)
sale

array([1900, 2640, 1430])