In [1]:
import numpy as np

In [2]:
a=np.array([3,4,5,6,7])
co=a.copy()#used to copy an np array 
print(a)
print()
print(co)

[3 4 5 6 7]

[3 4 5 6 7]


In [3]:
vi=a.view()
print(vi)

[3 4 5 6 7]


In [4]:
a[3]=60

In [6]:
print(co)#to put simply copy works like a call by value
print(vi)#and view works like a call by refrence

[3 4 5 6 7]
[ 3  4  5 60  7]
