In [2]:
import numpy as np

Shuffle

In [4]:
a=np.array([3,4,5,6,7,8,9])
print(a)
np.random.shuffle(a)#it will shuffle the array
print(a)

[3 4 5 6 7 8 9]
[6 7 3 9 8 4 5]


Unique

In [6]:
b=np.array([3,3,4,5,4,6,7,7,8,8,8,8,89,9,9])
print(b)
c=np.unique(b)#it will remove the duplicate values
print(c)

[ 3  3  4  5  4  6  7  7  8  8  8  8 89  9  9]
[ 3  4  5  6  7  8  9 89]


In [8]:
d=np.unique(b,return_index=True,return_counts=True)#it not only will remove the duplicate values also return the index of thr duplicate elements and their counts
print(d)

(array([ 3,  4,  5,  6,  7,  8,  9, 89]), array([ 0,  2,  3,  5,  6,  8, 13, 12], dtype=int64), array([2, 2, 1, 1, 2, 4, 2, 1], dtype=int64))


Resize

In [9]:
e=np.resize(a,(2,3))
print(e)

[[6 7 3]
 [9 8 4]]


Flatten

In [12]:
print(e)
print(e.flatten())#to convert an two dimensional array to one dimesional array

[[6 7 3]
 [9 8 4]]
[6 7 3 9 8 4]


In [20]:
print(e)
print(a.flatten(order="F"))

[[6 7 3]
 [9 8 4]]
[6 7 3 9 8 4 5]


In [21]:
print(e.flatten(order="A"))

[6 7 3 9 8 4 5]


In [22]:
print(e.flatten(order="K"))

[6 7 3 9 8 4 5]


In [18]:
print(e.flatten(order="C"))

[6 7 3 9 8 4]
