In [1]:
import numpy as np

In [3]:
a=np.array([3,4,5,6,7,8,9])
print(a)

[3 4 5 6 7 8 9]


In [4]:
print(a.dtype)

int32


In [10]:
np.insert(a,0,1)#to insert an element at a specific position

array([1, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.insert(a,(3,4),55)

array([ 3,  4,  5, 55,  6, 55,  7,  8,  9])

In [16]:
b=np.array([[3,4,5],[6,7,8]])
print(b)
c=np.insert(b,2,6,axis=0)
print(c)
d=np.insert(b,2,6,axis=1)
print(d)

[[3 4 5]
 [6 7 8]]
[[3 4 5]
 [6 7 8]
 [6 6 6]]
[[3 4 6 5]
 [6 7 6 8]]


In [17]:
e=np.insert(b,2,[45,46,47],axis=0)
print(e)

[[ 3  4  5]
 [ 6  7  8]
 [45 46 47]]


In [18]:
x=np.append(a,400)
print(x)

[  3   4   5   6   7   8   9 400]


In [22]:
y=np.append(b,[[67,68,69]],axis=0)
print(y)

[[ 3  4  5]
 [ 6  7  8]
 [67 68 69]]


Delete

In [23]:
print(a)

[3 4 5 6 7 8 9]


In [24]:
p=np.delete(a,0)#delete is used to delete an item from an array for that you need the index of the element
print(p)

[4 5 6 7 8 9]
