In [1]:
import numpy as np

Transpose

In [5]:
a=np.matrix([[3,4],[5,6],[7,8]])
print(a)
print()
b=np.transpose(a)#it changes the column to row and row to column
print(b)
print()
print(a.T)#it will also do the same

[[3 4]
 [5 6]
 [7 8]]

[[3 5 7]
 [4 6 8]]

[[3 5 7]
 [4 6 8]]


Swapaxes

In [9]:
print(np.swapaxes(a,0,1))#here 0 and 1 represents the conversion of row to column where row is 0 and column is 1

[[3 5 7]
 [4 6 8]]


Inverse

In [10]:
x=np.matrix([[3,4],[5,6]])
print(x)
print()

[[3 4]
 [5 6]]



In [11]:
print(np.linalg.inv(x))

[[-3.   2. ]
 [ 2.5 -1.5]]


Power

In [12]:
print(np.linalg.matrix_power(x,3))

[[267 332]
 [415 516]]


In [14]:
print(np.linalg.matrix_power(x,0))

[[1 0]
 [0 1]]


In [13]:
print(np.linalg.matrix_power(x,-3))

[[-64.5    41.5  ]
 [ 51.875 -33.375]]


Determinates

In [15]:
print(np.linalg.det(x))

-1.9999999999999971
