In [1]:
import numpy as np

In [2]:
x=[5,6,7,8]
y=np.array(x)
print(y)
print(type(y))

[5 6 7 8]
<class 'numpy.ndarray'>


Taking inputs from user for an numpy array

In [3]:
l=[]
for i in range(5):
    ele=int(input("Enter the elements:"))
    l.append(ele)

print(np.array(l))

[5 6 7 8 9]


Diff dimensions of numpy array

In [4]:
a=np.array([3,4,5,6])
print(a)
print(a.ndim)#ndim is used to check the dimesion of the np array

[3 4 5 6]
1


In [6]:
b=np.array([[4,5,6,7],[6,7,8,9]])
print(b)
print(b.ndim)

[[4 5 6 7]
 [6 7 8 9]]
2


In [7]:
c=np.array([[[4,5,6],[5,6,7],[6,7,8]]])
print(c)
print(c.ndim)

[[[4 5 6]
  [5 6 7]
  [6 7 8]]]
3


In [8]:
d=np.array([4,5,6,7],ndmin=10)#here i am creating 10 dimensional array with the help of ndmin 
print(d)
print(d.ndim)

[[[[[[[[[[4 5 6 7]]]]]]]]]]
10
