In [1]:
import numpy as np

Array filled with O's

In [2]:
ar_zero=np.zeros(4)#np.zeros is used to fill an array with all 0 values
print(ar_zero)

[0. 0. 0. 0.]


In [3]:
ar_zero2=np.zeros((3,4))#here i am creating an two dimesional array with all zero values
print(ar_zero2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
ar_zero3=np.zeros((10,3,4))#if we give three values then the first one will rep dim, second and third will no of row and col
print(ar_zero3)
print(ar_zero3.ndim)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
3


Array filled with I's

In [11]:
ar_ones=np.ones(5)#np.ones is used to fill an array with all 1 values
print(ar_ones)

[1. 1. 1. 1. 1.]


In [12]:
ar_ones2=np.ones((5,6))
print(ar_ones2)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [13]:
ar_ones3=np.ones((3,4,5))
print(ar_ones3)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


Create an empty array

In [14]:
ar_empty=np.empty(5)#np.empty s used to create an empty array, here the output is one because it takes the imput of previously used memory
print(ar_empty)

[1. 1. 1. 1. 1.]


An array with a range of elements

In [15]:
ar_range=np.arange(5)#np.arrange is used to create an array of n elements
print(ar_range)

[0 1 2 3 4]


Array diagonal element filled with I's

In [16]:
ar_diagonal=np.eye(3)#np.eye is ised to create a two dim array with diagonal value as 1
print(ar_diagonal)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create an array with values that are spaced linearly in a specified interval

In [17]:
ar_lin=np.linspace(1,10,5)#np.linespace is used to create an array of given no of elements between a range like 1 to 10 is the range and 5 is the no of elements
print(ar_lin)

[ 1.    3.25  5.5   7.75 10.  ]
