In [1]:
import numpy as np

In [2]:
var1=np.array([4,5,6,7])
print(var1)
print(var1.dtype)#dtpe is used to find the data type

[4 5 6 7]
int32


In [4]:
var2=np.array([4.5,6.7])
print(var2)
print(var2.dtype)

[4.5 6.7]
float64


In [5]:
var3=np.array(['s','h','u','v'])
print(var3)
print(var3.dtype)

['s' 'h' 'u' 'v']
<U1


In [6]:
var4=np.array(['s','h','u','v',4,5,6,7])
print(var4)
print(var4.dtype)

['s' 'h' 'u' 'v' '4' '5' '6' '7']
<U11


Data Type Converting

In [8]:
x=np.array([4,5,6,7],dtype=np.int8)#here i am cpnverting from int 32 to int 8
print(x)
print(x.dtype)

[4 5 6 7]
int8


In [9]:
y=np.array([4,5,6,7],dtype="f")#here i am cpnverting from int 32 to float 32
print(y)
print(y.dtype)

[4. 5. 6. 7.]
float32


In [10]:
z=np.array([5.6,6.7,7.8])
new=np.int32(z)
print(z)
print(new)
print(z.dtype)
print(new.dtype)

[5.6 6.7 7.8]
[5 6 7]
float64
int32


In [18]:
d=np.array([5.6,6.7,7.8])
neww=d.astype("int")
print(d)
print(neww)
print(d.dtype)
print(neww.dtype)

[5.6 6.7 7.8]
[5 6 7]
float64
int32
