In [1]:
import numpy as np

In [3]:
a=np.array([[3,4],[5,6]])
print(a)
print(a.shape)#shape is used to find the spae of an particular np array

[[3 4]
 [5 6]]
(2, 2)


In [4]:
b=np.array([4,5,6,7],ndmin=5)
print(b)
print(b.shape)#here in the answer the 4 one's are rep rows and at last 4 means no of columns

[[[[[4 5 6 7]]]]]
(1, 1, 1, 1, 4)


Reshape

In [13]:
c=np.array([1,2,3,4,5,6,7,8,9])
d=c.reshape(3,3)#no of elements should be the multipication of row and column providing inside the reshape function
print(c)
print(d)
print(d.shape)
print(d.ndim)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2


In [15]:
e=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
f=e.reshape(3,2,2)#here the 3 is rep the no of dimensions, 2 and other 2 is rep the no of rows and columns 
print(e)
print(f)
print(f.shape)
print(f.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
(3, 2, 2)
3


In [16]:
g=f.reshape(-1)#here with the help of -1 i am respaing the 3 dim f np array to 1dim np array
print(g)
print(g.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1
