In [1]:
import numpy as np

In [2]:
a=np.array([3,4,5])
b=a+3
print(b)

[6 7 8]


In [8]:
c=np.array([6,7,8])
d=a+c
print(d)
print(np.add(a,c))

[ 9 11 13]
[ 9 11 13]


In [9]:
e=a-b
print(e)
print(np.subtract(a,b))

[-3 -3 -3]
[-3 -3 -3]


In [10]:
f=a*b
print(f)
print(np.multiply(a,b))

[18 28 40]
[18 28 40]


In [11]:
g=b/a
print(g)
print(np.divide(b,a))

[2.   1.75 1.6 ]
[2.   1.75 1.6 ]


In [13]:
h=b%a
print(h)
print(np.mod(b,a))

[0 3 3]
[0 3 3]


In [16]:
A=np.array([[3,4,5],[6,7,8]])
B=np.array([[4,5,6],[9,8,7]])
add=A+B
print(add)

[[ 7  9 11]
 [15 15 15]]


In [17]:
print(np.multiply(A,B))

[[12 20 30]
 [54 56 56]]
