In [1]:
import numpy as np
import pandas as pd

In [3]:
a=np.array([3,4,5,6,7])
print(a)
type(a)

[3 4 5 6 7]


numpy.ndarray

In [7]:
b=np.array([[3,4],[5,6]])
print(b)
type(b)
print(b.dtype)
print(b.ndim)

c=np.array([5,6,7,8],ndmin=6)
print(c)
print(c.ndim)

[[3 4]
 [5 6]]
int32
2
[[[[[[5 6 7 8]]]]]]
6


In [8]:
df=pd.read_csv("D:\\DATASETS\\Employee.csv")
df

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0           NaN         2017  Bangalore          3.0   34    Male          No   
1     Bachelors         2013       Pune          1.0   28  Female          No   
2     Bachelors         2014        NaN          3.0   38  Female         NaN   
3       Masters         2016  Bangalore          3.0   27    Male          No   
4       Masters         2017       Pune          3.0   24    Male         Yes   
...         ...          ...        ...          ...  ...     ...         ...   
4648  Bachelors         2013  Bangalore          3.0   26  Female          No   
4649    Masters         2013       Pune          2.0   37    Male          No   
4650    Masters         2018  New Delhi          3.0   27    Male          No   
4651  Bachelors         2012  Bangalore          3.0   30    Male         Yes   
4652  Bachelors         2015  Bangalore          3.0   33    Male         Yes   

      ExperienceInCurrentDomain LeaveOrNot  
0                           0.0         No  
1                           3.0        Yes  
2                           2.0         No  
3                           5.0        Yes  
4                           NaN        Yes  
...                         ...        ...  
4648                        4.0         No  
4649                        2.0        Yes  
4650                        5.0        Yes  
4651                        2.0         No  
4652                        4.0         No  

[4653 rows x 9 columns]

In [10]:
df.head(30)

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
0         NaN         2017  Bangalore          3.0   34    Male          No   
1   Bachelors         2013       Pune          1.0   28  Female          No   
2   Bachelors         2014        NaN          3.0   38  Female         NaN   
3     Masters         2016  Bangalore          3.0   27    Male          No   
4     Masters         2017       Pune          3.0   24    Male         Yes   
5   Bachelors         2016  Bangalore          3.0   22    Male          No   
6   Bachelors         2015  New Delhi          3.0   38    Male          No   
7   Bachelors         2016  Bangalore          3.0   34  Female         NaN   
8   Bachelors         2016       Pune          3.0   23    Male          No   
9     Masters         2017  New Delhi          2.0   37    Male          No   
10    Masters         2012  Bangalore          3.0   27     NaN          No   
11  Bachelors         2016       Pune          NaN   34    Male          No   
12  Bachelors         2018       Pune          3.0   32    Male         Yes   
13  Bachelors         2016  Bangalore          3.0   39    Male          No   
14  Bachelors         2012  Bangalore          3.0   37    Male          No   
15  Bachelors         2017  Bangalore          1.0   29    Male          No   
16  Bachelors         2014  Bangalore          3.0   34  Female          No   
17  Bachelors         2014       Pune          3.0   34    Male          No   
18  Bachelors         2015       Pune          NaN   30  Female          No   
19  Bachelors         2016  New Delhi          2.0   22  Female          No   
20  Bachelors         2012  Bangalore          3.0   37    Male          No   
21    Masters         2017  New Delhi          2.0   28    Male          No   
22  Bachelors         2017  New Delhi          2.0   36    Male          No   
23  Bachelors         2015  Bangalore          3.0   27    Male         Yes   
24  Bachelors         2017  Bangalore          3.0   29    Male          No   
25  Bachelors         2013  Bangalore          3.0   22  Female         Yes   
26  Bachelors         2016  Bangalore          3.0   37    Male          No   
27  Bachelors         2015  Bangalore          3.0   23    Male          No   
28  Bachelors         2013       Pune          2.0   31  Female          No   
29    Masters         2017  New Delhi          2.0   30  Female          No   

    ExperienceInCurrentDomain LeaveOrNot  
0                         0.0         No  
1                         3.0        Yes  
2                         2.0         No  
3                         5.0        Yes  
4                         NaN        Yes  
5                         0.0         No  
6                         0.0         No  
7                         2.0        Yes  
8                         1.0         No  
9                         NaN         No  
10                        5.0        Yes  
11                        3.0         No  
12                        5.0        Yes  
13                        2.0         No  
14                        4.0         No  
15                        3.0        NaN  
16                        2.0         No  
17                        4.0         No  
18                        0.0        NaN  
19                        0.0        Yes  
20                        0.0         No  
21                        4.0         No  
22                        3.0         No  
23                        5.0         No  
24                        4.0         No  
25                        0.0         No  
26                        2.0         No  
27                        1.0         No  
28                        2.0        Yes  
29                        2.0         No

In [11]:
df.tail()

Education  JoiningYear       City  PaymentTier  Age  Gender EverBenched  \
4648  Bachelors         2013  Bangalore          3.0   26  Female          No   
4649    Masters         2013       Pune          2.0   37    Male          No   
4650    Masters         2018  New Delhi          3.0   27    Male          No   
4651  Bachelors         2012  Bangalore          3.0   30    Male         Yes   
4652  Bachelors         2015  Bangalore          3.0   33    Male         Yes   

      ExperienceInCurrentDomain LeaveOrNot  
4648                        4.0         No  
4649                        2.0        Yes  
4650                        5.0        Yes  
4651                        2.0         No  
4652                        4.0         No

In [22]:
ndf=pd.read_csv("C:\\Users\\hp\\Documents\\nnn.csv",delimiter='\t',names=['col','col4'])
ndf

col col4
0     1    e
1     2    r
2     3    t
3     4    f
4     5    g
5     6    h
6     7    i
7     8    u
8     9    v
9    10    q
10   11    a
11   12    d
12   13    e
13   14    d
14   15    s
15   16    t
16   17    y
17   18    a
18   19    z
19   20    x